# Understanding Hypothesis Testing

- [DS C54 - Hypothesis Testing Session](https://live.upgrad.com/summary/7phUTHzI6ZIHN3RIuKluHypkoUhI38dP)

- [DS C54 Statistics Career Session](https://live.upgrad.com/summary/3ymYR2xuzyl6pYtEsjtUpaKxw89sqsWN)

- ## [Z - Table](https://cdn.upgrad.com/UpGrad/temp/fa97ec8c-c699-4677-b0d8-de24a87e096c/z-table.pdf)

Nature of hypotheses
--------

Which of the following is true about the two hypotheses that were just stated?

    Exactly one hypothesis must be true

    Both hypotheses must be true

    It is possible for neither hypothesis to be true

    It is possible for both hypotheses to be true

---------

    Exactly one hypothesis must be true

    ✓ Correct
    Feedback:

Both the hypotheses oppose each other, so only one of the two can be true.

----------

    Let’s understand the basic difference between
    inferential statistics and hypothesis testing.


`Inferential statistics` is used to find some population parameter (mostly population mean) when you have no initial number to start with.

So, you start with the sampling activity and find out the sample mean.

Then, you estimate the population mean from the sample mean using the confidence interval.


`Hypothesis testing` is used to confirm your conclusion (or hypothesis) about the population parameter (which you know from EDA or your intuition).

Through hypothesis testing, you can determine whether there is enough evidence to conclude if the hypothesis about the population parameter is true or not.

    Hypothesis Testing starts with the formulation of these two hypotheses:

**Null hypothesis (H₀)**: The status quo

**Alternate hypothesis (H₁)**: The challenge to the status quo

Null and Alternate Hypotheses
--------

In the Maggi Noodles example, if you **fail to reject the null hypothesis**, what can you conclude from this statement?

    Maggi Noodles contain excess lead

    Maggi Noodles do not contain excess lead

----------

    Maggi Noodles do not contain excess lead

    ✓ Correct
    Feedback:

The null hypothesis is that the average lead content is less than or equal to 2.5 ppm.

Since you fail to reject the null hypothesis, you can conclude that Maggi Noodles do not contain excess lead.

Please note than you can only fail to reject the null hypothesis, you can never accept the null hypothesis.

Types of Hypotheses
-------

The null and alternative hypotheses divide all possibilities into:

    2 sets that overlap

    2 non-overlapping sets

    2 sets that may or may not overlap

    As many sets as necessary to cover all possibilities

---------------

    2 non-overlapping sets

    ✓ Correct
    Feedback:

Both the null and alternate hypotheses can’t be true at the same time.

Only one of them will be true.

# Null and Alternate Hypotheses

    You can use the following rule to formulate the null and alternate hypotheses:

![ss](https://cdn.upgrad.com/UpGrad/temp/c4470702-bb94-4f69-b8cc-6aea9ad17be7/1.png)

- The null hypothesis always has the following signs:  `=  OR   ≤   OR    ≥`

![ss](https://cdn.upgrad.com/UpGrad/temp/33e308ba-2bd8-43a8-bcfe-e53a1e768cf2/1b.png)

- The alternate hypothesis always has the following signs:  `≠   OR  >   OR    <`

Null and Alternate Hypotheses
----------

Flipkart claimed that its total valuation in December 2016 was $14 billion.

What would be the alternate hypothesis for the given situation?

    H₁: Total valuation = $14 billion

    H₁: Total valuation < $14 billion

    H₁: Total valuation > $14 billion

    H₁: Total valuation ≠ $14 billion

----------

    H₁: Total valuation ≠ $14 billion

    ✓ Correct
    Feedback:

The null hypothesis in this case would be that the total valuation is equal to $14 billion.

Hence the alternate hypothesis is the `opposite` of that.

Null and Alternate Hypotheses
------------

The average commute time for an UpGrad employee to and from office is `at least 35` minutes.

What will be the null and alternate hypotheses in this case if the average time is represented by μ?

    H₀: μ ≤ 35 minutes and H₁: μ > 35 minutes

    H₀: μ > 35 minutes and H₁: μ ≤ 35 minutes

    H₀: μ ≥ 35 minutes and H₁: μ < 35 minutes

    H₀: μ < 35 minutes and H₁: μ ≥ 35 minutes

-----------

    H₀: μ ≥ 35 minutes and H₁: μ < 35 minutes

    ✓ Correct
    Feedback:

The null hypothesis is `always formulated` by either = or ≤ or ≥ whereas the alternate hypothesis is formulated by ≠ or > or <.

In this case, the average time taken was `greater than or equal to 35` minutes.

So, that becomes the `null hypothesis`.

`Less than 35` minutes becomes the alternate hypothesis.

Null and Alternate Hypotheses
----------

Goodyear claims that each of its tyres can travel more than 7500 miles on average before they need any replacement.

Assuming that the average travel distance is given by μ, what would be the null and the alternate hypothesis in this case?

    H₀: μ > 7500 miles and H₁: μ ≤ 7500 miles

    H₀: μ ≥ 7500 miles and H₁: μ < 7500 miles

    H₀: μ < 7500 miles and H₁: μ ≥ 7500 miles

    H₀: μ ≤ 7500 miles and H₁: μ > 7500 miles

----------

    H₀: μ  ≤  7500 miles and H₁: μ > 7500 miles

    ✓ Correct
    Feedback:

The null hypothesis is always formulated by either = or ≤ or ≥ whereas the alternate hypothesis is formulated by ≠ or > or <.

If you check the claim statement, it has the > sign (i.e. μ > 7500 miles).

Hence the null hypothesis would be the complement of the claim statement

    i.e. μ ≤ 7500 miles,

and the alternate hypothesis would be the claim statement itself

    or μ > 7500 miles.

Null and Alternate Hypotheses
--------

What would be the null and alternate hypotheses for Apurva’s claim?

    H₀: μ = 70 and H₁: μ ≠ 70

    H₀: μ ≠ 70 and H₁: μ = 70

    H₀: μ ≤ 70 and H₁: μ > 70

    H₀: μ ≥ 70 and H₁: μ < 70

---------

    H₀: μ = 70 and H₁: μ ≠ 70

    ✓ Correct
    Feedback:

The null hypothesis is always formulated by either = or ≤ or ≥.

Here, Apurva’s claim is that her score is `equal to 70`, so that would become the null hypothesis.

And alternate hypothesis would be that her score is `not equal to 70`.

Making a decision
----------

If your sample mean lies in the acceptance region, then:

    You reject the null hypothesis

    You fail to reject the null hypothesis

---------

    You fail to reject the null hypothesis

    ✓ Correct
    Feedback:

If your sample mean lies in the acceptance region,

you fail to reject the null hypothesis

because it is not beyond the critical point

and you can consider that sample mean is equal to the population mean statistically.

You can tell the `type of the test` and the `position of the critical region` on the basis of the ‘`sign`’ in the `alternate hypothesis`.
----------

    ≠ in H₁    →   Two-tailed test        →     Rejection region on both sides of distribution

    < in H₁    →   Lower-tailed test     →     Rejection region on left side of distribution

    > in H₁    →   Upper-tailed test     →     Rejection region on right side of distribution

Types of tests
-------

Government regulatory bodies have specified that the maximum permissible amount of lead in any food product is 2.5 parts per million or 2.5 ppm.

If you conduct tests on randomly chosen Maggi Noodles samples from the market to see if its lead content is above the permissible amount of 2.5 ppm, what type of test this would be?

    Two-tailed test

    Lower-tailed test

    Upper-tailed test

-----------

    Upper-tailed test

    ✓ Correct
    Feedback:

Null hypothesis says, maximum permissible amount is 2.5 ppm, (`means, μ ≤ 2.5`)

The alternate hypothesis in this case would be that the average lead content is more than 2.5 ppm, (`means, μ > 2.5`)

The critical region would lie on right side of distribution,

as if lead content is too lower than 2.5 ppm then it's a good news,

hence we don't need to test on left side of distribution.

So this would be an upper-tailed test, (considering alternate hypothesis only).

Here, you can notice that `alternate hypothesis is formulated with “more than”` argument (equivalently > sign),

which justifies it being a right-tailed test.

Null and Alternate Hypotheses
-----------

The average commute time for an UpGrad employee to and from office is at least 35 minutes.

If this hypothesis has to be tested, select the type of the test and the location of the critical region.

    Lower-tailed test, with the rejection region on the right side

    Upper-tailed test, with the rejection region on the right side

    Lower-tailed test, with the rejection region on the left side

    Upper-tailed test, with the rejection region on the left side

----------

    Lower-tailed test, with the rejection region on the left side

    ✓ Correct
    Feedback:

For this situation, the hypotheses would be formulated as

    H₀: μ ≥ 35 minutes and H₁: μ < 35 minutes.

As `< sign` is used in alternate hypothesis, it would be a lower-tailed test

and the rejection region would be on the left side of the distribution.

Null and Alternate Hypotheses
---------

A courier claims that the average delivery time of goods is 3 days.

Choose the correct formulation of hypothesis along with the correct test.

    H 0 : μ ≠ 3 ; H 1 : μ = 3 ; T e s t : T w o − t a i l e d t e s t

    H 0 : μ = 3 ; H 1 : μ ≠ 3 ; T e s t : L o w e r − t a i l e d t e s t

    H 0 : μ = 3 ; H 1 : μ ≠ 3 ; T e s t : U p p e r − t a i l e d t e s t

    H 0 : μ = 3 ; H 1 : μ ≠ 3 ; T e s t : T w o − t a i l e d t e s t

-----------

    H 0 : μ = 3 ; H 1 : μ ≠ 3 ; T e s t : T w o − t a i l e d t e s t

    ✓ Correct
    Feedback:

H0 always has an equal sign.

And since H1 has an unequal sign, we need to test both the sides.

Null and Alternate Hypotheses
--------------

A researcher claims that the weight of an average male Bengal tiger is less than 220 KG.

    H 0 : μ >= 220 k g , H 1 : μ < 220 k g , T e s t : U p p e r − t a i l e d t e s t

    H 0 : μ < 220 k g , H 1 : μ ≥ 220 k g , T e s t : U p p e r − t a i l e d t e s t

    H 0 : μ > 220 k g , H 1 : μ ≤ 220 k g , T e s t : L o w e r − t a i l e d t e s t

    None of the above

--------

    None of the above

    ✓ Correct
    Feedback:

The correct formulation is as follows:

    H 0 : μ >= 220 k g , H 1 : μ < 220 k g , T e s t : L o w e r − t a i l e d t e s t

--------------

    Does the claim statement directly give the null hypothesis?

`No`, you have to check whether the claim statement has an

    "equal to",

    "greater than equal to" or

    "less than equal to"

symbol and then on the basis of that decide whether the claim statement

or the complement of it would become the null hypothesis.

# Critical Value Method

Standard deviation
----------

What will be the standard deviation of the distribution of sample means

if the population has a mean of 350 and a standard deviation of 90, a sample mean of 370.16, and a sample size of 36?

    9.72

    2.5

    15

    3.88

---------

    15

    ✓ Correct
    Feedback:

The standard deviation of a distribution of sample means is obtained by dividing the population standard deviation by the square root of the sample size.

    So, 90 / √36 = 90/6 = 15

In [ ]:
90 / (36 ** 0.5)

15.0

Area of rejection region
----------

What will be the area of the critical region on the `right-hand side` of the distribution if the significance level `(α) for a two-tailed test is 3%`?

    0.03

    0.97

    0.015

    0.985

-----------

    0.015

    ✓ Correct
    Feedback:

Here, value of `α is 0.03` (of 3%),

so the `area of the rejection` region would be 0.03

and the `area of the acceptance` region would be 0.97

In addition, since this is a `two-tailed test`,

the area of the critical region on the right-hand side would be `half of 0.03`,

    i.e. 0.015

Area of rejection region
-------

What would be the area of the critical region on the right-hand side of the distribution if the significance level (α) for an upper-tailed test is 3%?

    0.03

    0.97

    0.015

    0.985

--------

    0.03

    ✓ Correct
    Feedback:

Here, the value of α is 0.03 (of 3%), so the area of the critical region would be 0.03 and the area of the acceptance region would be 0.97

Since this is an upper-tailed test, the critical region is only on the right-hand side of the distribution, and the area of the critical region would be 0.03

Area of rejection region
----------

What would be the value of the cumulative probability of UCV if the significance level (α) for an upper-tailed test is 3%?

    0.03

    0.97

    0.015

    0.985

-----

    0.97

    ✓ Correct
    Feedback:

The area of the critical region in this case would be 0.03 (as calculated in the last question),

which would be the area beyond the UCV point in the distribution.

So, the area till the UCV point would be `1 - 0.03, i.e. 0.97`.

This would be the cumulative probability of that point,

going by the definition of cumulative probability.

Let’s solve the following problem stepwise
----------

A manufacturer claims that the `average` life of its product is `36 months`.

An auditor selects a `sample of 49 units` of the product, and calculates the average life to be `34.5 months`.

The population `standard deviation is 4 months`.

Test the manufacturer’s claim at `3% significance level` using the critical value method.

First, you need to formulate the hypotheses for this `two-tailed test`, which would be:

    H₀:μ = 36 months and H₁: μ ≠ 36 months

Critical Value Method
-------

    1st step:

Calculate the value of Zc from the given value of α (significance level).

Calculate the z-critical score for the two-tailed test at 3% significance level.

    1.88

    1.04

    2.965

    2.17

----------

    2.17

    ✓ Correct
    Feedback:

For 3% significance level, you would have two critical regions on both sides with a total area of 0.03

So, the area of the critical region on the right side would be 0.015,

which means that the area till UCV (cumulative probability of that point) would be 1 - 0.015 = 0.985

So, you need to find the z-value of 0.985.

The z-score for 0.9850 in the `z-table` is 2.17 ( = 2.1 + 0.07)

(2.1 on the horizontal axis and 0.07 on the vertical axis)

Critical Value Method
---------

    2nd step:

Calculate the critical values (UCV and LCV) from the value of Zc.

Find out the UCV and LCV values for Zc = 2.17.

- μ = 36 months
- σ = 4 months
- n (Sample size) = 49


    UCV = 37.24 and LCV = 34.76

    UCV = 36.18 and LCV = 35.82

    UCV = 44.68 and LCV = 27.32

    UCV = 36.31 and LCV = 35.69

------

    UCV = 37.24 and LCV = 34.76

    ✓ Correct
    Feedback:

The critical values can be calculated from

    μ ± Zc * (σ / √ N​)
    as 36 ± 2.17 * (4 / ​√ 49​)
    = 36 ± 1.24

which comes out to be `37.24 and 34.76`

In [ ]:
def con_int(n, x, s, z):
  ci = (z * s) / (n ** 0.5)
  return x - ci, x + ci

In [ ]:
n, x, s, z = 49, 36, 4, 2.17
ci = con_int(n, x, s, z)
ci

(34.76, 37.24)

In [ ]:
import numpy as np
np.array(ci).mean()

36.0

Critical Value Method
----------

    3rd step:

Make the decision on the basis of the value of the sample mean X with respect to the critical values (UCV AND LCV).

What would be the result of this hypothesis test?

- UCV = 37.24 months
- LCV = 34.76 months
- Sample mean (x) = 34.5 months


    Fail to reject the null hypothesis

    Reject the null hypothesis

    Can’t say

----------

    Reject the null hypothesis

    ✓ Correct
    Feedback:

The UCV and LCV values for this test are 37.24 and 34.76

The sample mean in this case is `34.5 months`, which is less than LCV.

So, this implies that the `sample mean lies in the critical region`

and you can `reject the null hypothesis`.

# Critical Value Method - Examples

Type of test
-----------

Consider this problem —

    H₀: μ ≤ 350 and H₁: μ > 350

Can you tell what kind of test it would be?

    Two-tailed test

    One-tailed test

------------

    One-tailed test

    ✓ Correct
    Feedback:

The > sign means that the critical region is on the right-hand side (versus both the sides)

and, therefore, you only need to use a one-tailed test.

Critical Value Method
-------------

Consider this problem —

    H₀: μ ≤ 350 and H₁: μ > 350

In case of a two-tailed test, you find the z-score of 0.975 in the z-table,

since 0.975 was cumulative probability of UCV in that case.

In this problem, what would be the cumulative probability of critical point in this example for the same significance level of 5%?

    0.975

    0.025

    0.950

    0.050

------------

    0.950

    ✓ Correct
    Feedback:

In this problem, the area of the critical region beyond the only critical point, which is on the `right side`, is 0.05 (in the last problem, it was 0.025).

So, the cumulative probability of the critical point (the total area till that point) would be 0.950.

Critical Value Method
----------

Consider this problem —

    H₀: μ ≤ 350 and H₁: μ > 350

The next step would be to find the Zc, which would basically be the z-score for the value of 0.950.

Look at the z-table and find the value of Zc.

    1.64

    1.645

    1.65

    1.96

-----------

    1.645

    ✓ Correct
    Feedback:

0.950 is `not` there in the z-table.

So, look for the numbers `nearest` to 0.950.

You can see that the z-score for 0.9495 is 1.64

(1.6 on the horizontal bar and 0.04 on the vertical bar),

and the z-score for 0.9505 is 1.65.

So, taking the `average` of these two, the z-score for 0.9500 is 1.645

Critical Value Method
--------

Consider this problem,

    H₀: μ ≤ 350 and H₁: μ > 350

So, the Zc comes out to be 1.645.

Now, find the critical value for the given Zc and make the decision to accept or reject the null hypothesis.

- μ = 350
- σ = 90
- N (Sample size) = 36
- x = 370.16


    Critical value = 374.67 and
    Decision = Reject the null hypothesis

    Critical value = 326.25 and
    Decision = Reject the null hypothesis

    Critical value = 374.67 and
    Decision = Fail to reject the null hypothesis

    Critical value = 326.25 and
    Decision = Fail to reject the null hypothesis

-----------

    Critical value = 374.67 and
    Decision = Fail to reject the null hypothesis

    ✓ Correct
    Feedback:

The critical value can be calculated from

    μ + Zc * (σ / √ N )
    350 + 1.645 * (90/ √ 36 )
    = 374.67

Since 370.16 `( x ) is less than` 374.67, x lies in the acceptance region

and you fail to reject the null hypothesis.

In [ ]:
n, μ, s, z = 36, 350, 90, 1.645
x = 370.16

ci = con_int(n, μ, s, z)
ci

(325.325, 374.675)

In [ ]:
x < ci[1]

True

Given
------

Government regulatory bodies have specified that the `maximum` permissible amount of lead in any food product is 2.5 parts per million or 2.5 ppm.

Let’s say you are an analyst working at the food regulatory body of India FSSAI.

Suppose you take 100 random samples of Sunshine from the market and have them tested for the amount of lead.

    The mean lead content turns out to be 2.6 ppm
    with a standard deviation of 0.6.



One thing you can notice here is that the standard deviation of the sample is given as 0.6, instead of the population’s standard deviation.

In such a case, you can approximate the population’s standard deviation to the sample’s standard deviation, which is 0.6 in this case.


Answer the following questions in order to find out if a regulatory alarm should be raised against Sunshine or not, at `3% significance` level.

Critical Value Method
--------

Select the correct null and alternate hypotheses in this case.

    H₀: Average lead content ≤ 2.6 ppm and
    H₁: Average lead content > 2.6 ppm

    H₀: Average lead content ≤ 2.5 ppm and
    H₁: Average lead content > 2.5 ppm

    H₀: Average lead content ≥ 2.6 ppm and
    H₁: Average lead content < 2.6 ppm

    H₀: Average lead content ≥ 2.5 ppm and
    H₁: Average lead content < 2.5 ppm

---------

    H₀: Average lead content ≤ 2.5 ppm and
    H₁: Average lead content > 2.5 ppm

    ✓ Correct
    Feedback:

The null hypothesis is your assumption about the population — it is based on the status quo.

It always makes an argument about the population using the equality sign.

The null hypothesis in this case would be that the average lead content in the food material is `less than or equal` to 2.5 ppm (`maximum`).

And the alternate hypothesis is that the average lead content is greater than 2.5 ppm.

Critical Value Method
------------

Calculate the z-critical score for this test at 3% significance level.

    1.88

    1.555

    2.965

    2.17

-----------

    1.88

    ✓ Correct
    Feedback:

This is a `one-tailed test`.

So, for 3% significance level, you would have only one critical region on the `right side` with a total area of 0.03

This means that the area till the critical point

(the cumulative probability of that point) would be

    1 - 0.030 = 0.970

So, you need to find the `z-value of 0.970`

The z-score for 0.9699 (~0.970) in the z-table is `1.88`

Critical Value Method
--------

Now, you need to find out the critical values and make a decision on whether to raise a regulatory alarm against Sunshine or not.

Select the correct option.

    Critical value = 2.61 ppm and
    Decision: Raise a regulatory alarm

    Critical value = 2.63 ppm and
    Decision: Raise a regulatory alarm

    Critical value = 2.61 ppm and
    Decision: Don’t raise a regulatory alarm

    Critical value = 2.63 ppm and
    Decision: Don’t a raise a regulatory alarm

---------

    Critical value = 2.61 ppm and
    Decision: Don’t raise a regulatory alarm

    ✓ Correct
    Feedback:

The critical value can be calculated from μ + Zc * (σ / ​√ N​),

as 2.5 + 1.88 * (0.6 /​√ 100​) = 2.61 ppm

You need to use the `+ sign` since the critical value is on the `right-hand side` (upper-tailed test).

    Since the sample mean 2.6 ppm is less than the critical value (2.61 ppm),

you fail to reject the null hypothesis and `don’t raise a regulatory alarm` against Sunshine.

In [ ]:
n, μ, s, z = 100, 2.5, 0.6, 1.88
x = 2.6

ci = con_int(n, μ, s, z)
ci

(2.3872, 2.6128)

In [ ]:
x < ci[1]

True

Critical Value Method
--------

The critical value for this test at 3% significance level comes out to be 2.61 ppm.

If you take more than 100 samples

(with the same sample mean and standard deviation),

how would the z-score and critical value change?

    Both the z-score and
    the critical value would increase

    The z-score would remain the same but
    the critical value would increase

    The z-score would remain the same but
    the critical value would decrease

    Both the z-score and
    the critical value would remain the same

----------

    The z-score would remain the same but
    the critical value would decrease

    ✓ Correct
    Feedback:

Since Zc is calculated from the given value of `α (3%)`, it remains the `same`.

Critical value is calculated using the formula: `μ + Zc * (σ / ​√ N​)`, since it is an `upper-tailed test`.

If you increase the value of N, the critical value would `decrease` according to the formula.

# What exactly is the value of σ/√n?

------------

This part might seem a bit confusing if you aren't thorough with the concepts of Sampling distribution from the Inferential Statistics module.

This value of `σ/√n` isn't the standard deviation of the sample or

the population but rather it is the standard deviation of the sampling distribution for the given sample.

We conduct our hypothesis test on the sampling distribution only.

Thus when the standard deviation of the population isn't given, we take the sample's standard deviation to calculate the sampling distribution's standard deviation.

This is a very important concept to know and you should be pretty confident in how we are manipulating the values here.

We used this same concept in calculating the confidence intervals.

In that case we used `S/√n` instead which denoted that we can only use the sample's standard deviation in that case.