# Introduction

- ## [Z - Table](https://cdn.upgrad.com/UpGrad/temp/0ed10b23-e5f1-4299-9302-39658c3a4e56/z-table.pdf)

In [ ]:
# https://jovian.com/ashutoshgole18/module-9-hypothesis-testing/v/5#C69

def con_int(n, x, s, z):
  ci = (z * s) / (n ** 0.5)
  return x - ci, x + ci

n, μ, s, z = 100, 60, 10.7, 2.33
x = 62.6

ci = con_int(n, μ, s, z)
ci

(57.5069, 62.4931)

Critical Score
-------

Mark all the options that you think are correct for critical value and the p-value method.

    In the critical value method, the z-score,
    which is called Zc, is calculated for the critical points.

    In the critical value method, the z-score,
    which is called Zc, is calculated for the sample mean.

    In the p-value method,
    the z-score is calculated for the critical points.

    In the p-value method,
    the z-score is calculated for the sample mean.

------------

- In the critical value method, the z-score, which is called Zc, is calculated for the critical points.


    ✓ Correct
    Feedback:

    α is used to calculate the Zc value for the critical points in this method.

- In the p-value method, the z-score is calculated for the sample mean.


    ✓ Correct
    Feedback:

    In the p value method, the z-score is calculated for the sample mean.

p-value method
--------

To find the correct p-value from the z-score, find the **cumulative probability** first, by simply looking at the z-table, which gives you the area under the curve till that point.

`Situation 1:`

The sample mean is on the right side of the distribution mean (the z-score is `positive`).

*Example*: z-score for sample point = + 3.02

![ss](https://cdn.upgrad.com/UpGrad/temp/0ad46a72-29b4-4873-aa92-03e5a702fcee/2.png)

Cumulative probability of the sample point = 0.9987

    For a one-tailed test:
    p = 1 - 0.9987 = 0.0013

    For a two-tailed test:
    p = 2 (1 - 0.9987)
    = 2 * 0.0013 = 0.0026

`Situation 2:`

The sample mean is on the `left side` of the distribution mean (the z-score is `negative`).

*Example*: The z-score for the sample point = -3.02

![ss](https://cdn.upgrad.com/UpGrad/temp/4cccb6a8-8e0b-472f-9c5c-4defa7ff6220/3.png)

Cumulative probability of the sample point = 0.0013

    For a one-tailed test:
    p = 0.0013

    For a two-tailed test:
    p = 2 * 0.0013 = 0.0026

# Given

-----

You are working as a data analyst at an auditing firm.

A manufacturer claims that the `average life` of its product is `36 months`.

An auditor selects a `sample of 49 units` of the product and calculates the average life to be `34.5 months`.

The population `standard deviation is 4 months`.

Test the manufacturer’s claim at a `3% significance` level using the p-value method.

First, `formulate the hypothesis` for this `two-tailed test`, which would be:

    H₀: μ = 36 months and H₁: μ ≠ 36 months

Now, you need to follow the three steps to find the p-value and make a decision.

Try out the `three-step process` by answering the following questions.

The p-Value Method
--------

`Step 1:`

Calculate the value of the z-score for the sample mean point of the distribution.

Calculate the z-score for the sample mean (x) = 34.5 months.

    0.86

    -0.86

    2.62

    -2.62

---------

    -2.62

    ✓ Correct
    Feedback:

You can calculate the z-score for the `sample mean of 34.5` months using the formula:

    (x - μ)/(σ/​√ n)

This gives you

    (34.5 - 36) / (4/ √ 49 )
    = (-1.5) * 7/4
    = -2.62

Notice that since the sample mean lies on the left side of the hypothesised mean of 36 months, the z-score comes out to be negative.

In [ ]:
μ = 36
x = 34.5
s = 4
n = 49

S = s / (n ** 0.5)
S

0.5714285714285714

In [ ]:
# Ans.

z = (x - μ) / S
z

-2.625

In [ ]:
ci = con_int(n, μ, s, z)
ci

(37.5, 34.5)

The p-Value Method
--------

`Step 2:`

Calculate the p-value from the cumulative probability for the given z-score using the z-table.

Find out the p-value for a `z-score of -2.62` (corresponding to the `sample mean of 34.5` months).

`Hint:`

The sample mean is on the `left side` of the distribution, and it is a `two-tailed` test.

    0.0044

    0.9956

    0.0088

    1.9912

----

    0.0088

    ✓ Correct
    Feedback:

The value in the z-table corresponding to *-2.6 on the vertical axis and 0.02 on the horizontal axis* is 0.0044

Since the sample mean is on the left side of the distribution and this is a `two-tailed` test, the p-value would be:

    2 * 0.0044 = 0.0088

The p-Value Method
---------

`Step 3:`

Make the decision on the basis of the p-value with respect to the given value of α (significance value).

What would the result of this hypothesis test be?

    Fail to reject the null hypothesis

    Reject the null hypothesis

------------

    Reject the null hypothesis

    ✓ Correct
    Feedback:

Here, the p-value comes out to be `2 * 0.0044 = 0.0088`

Since the `p-value is less` than the significance level `(0.0088 < 0.03)`,

you reject the null hypothesis that the average lifespan of the manufacturer's product is 36 months.

FREQUENTLY ASKED QUESTIONS (FAQ)
--------

    Does p-value signify a probability for the null hypothesis?

Even though a higher p-value would show more evidence in favour of the null hypothesis,

it does not outrightly mean that the p-value is the probability of the null hypothesis being true and we are failing to reject it.

Always remember the technical definition of p-value -

the probability of observing a similar or more extreme observation given the null hypothesis is true.

    I am confused about how to calculate the standard deviation in
    the case where the sample's standard deviation is already given.

This confusion might be due to the misunderstanding of what exactly we are calculating with the formula of `σ/√n`.

We aren't calculating the `sample's standard deviation` with the previous formula.

Rather we are calculating the `sampling distribution's standard deviation`.

This is the distribution on which we conduct all our hypothesis tests and this is also the case for the critical value method as well.

So, in general if the population's standard deviation is not given,

the value of σ is approximated as the sample's standard deviation to `calculate` the sampling distribution's standard deviation

so that we can continue with the hypothesis test.

# The p-value Method: Examples

The p-Value Method
----------

Calculate the Z-score for the sample mean (x) = 510 mg.

    36.67

    -36.67

    -2.73

    2.73

----------

    2.73

    ✓ Correct
    Feedback:

The amount of paracetamol `deemed` safe by the drug regulatory authorities is 500 mg.

The standard deviation of the sample of 900 is given as 110 instead of the population standard deviation.

In such a case, you can assume the `population standard deviation` to be the same as the `sample standard deviation`, which is 110 in this case.

You can calculate the Z-score for the `sample mean` of 510 mg using the formula:

    (x - μ) / (σ / ​√ N)

This gives you

    (510 - 500) / (110 / √ 900 )
    = (10) / (110 / 30)
    = 2.73

Notice that since the sample mean lies on the right side of the hypothesised mean of 500 mg,

the Z-score comes out to be positive.

The p-Value Method
--------

Find out the p-value for the Z-score of 2.73 (corresponding to the sample mean of 510 mg).

    0.0032

    0.0064

    0.9968

    1.9936

-----------

    0.0064

    ✓ Correct
    Feedback:

The value in the Z-table corresponding to `2.7 on the vertical axis` and `0.03 on the horizontal axis` is 0.9968.

Since the sample mean is on the `right side` (x > μ, z > 0) of the distribution and this is a `two-tailed` test

(because we want to test whether the value of the paracetamol is `too low or too high`),

the p-value would be

    2 * (1 - 0.9968)
    = 2 * 0.0032
    = 0.0064

The p-Value Method
-----------

Based on this hypothesis test, what decision would you make about the manufacturing process?

    The manufacturing process is completely fine and need not be changed.

    The manufacturing process is not fine, and changes need to be made.

----------

    The manufacturing process is not fine, and changes need to be made.

    ✓ Correct
    Feedback:

Here, the p-value comes out to be 0.0064

Here, the p-value is less than the significance level (`0.0064 < 0.05`) and

    a smaller p-value gives you greater evidence against the null hypothesis.

So, you `reject the null hypothesis` that the average amount of paracetamol in medicines is 500 mg.

So, this is a regulatory alarm for the company, and the manufacturing process `needs to change`.

# Given

-------

A nationwide survey `claimed` that the unemployment rate of a country is `at least 8%`.

However, the government claimed that the survey was `wrong` and the unemployment rate is less than that.

The government asked about `36 people`, and the unemployment rate came out to be `7%`.

The population `standard deviation is 3%`.

Null and Alternative Hypotheses
-----------

[Doubt](https://learn.upgrad.com/course/4460/segment/34999/214308/657378/3330776)

What are the null and alternative hypotheses in this case?

    H 0 : μ ≥ 8 % and
    H 1 : μ < 8 %

    H 0 : μ ≤ 8 % and
    H 1 : μ > 8 %

    H 0 : μ > 8 % and
    H 1 : μ ≤ 8 %

    None of the above

--------

    H 0 : μ ≥ 8 % and
    H 1 : μ < 8 %

    ✓ Correct
    Feedback:

The null hypothesis must contain a `= sign`.

The two arithmetic signs possible in this scenario are >= or <.

Since >= has an equal to sign it becomes the null hypothesis.

Z-Score of the Sample Mean
---------

Based on the information above, conduct a hypothesis test at a 5% significance level using the p-value method.

What is the Z-score of the sample mean point x = 7%?

    -0.2

    2.0

    -2.0

    0.2

--------

    -2.0

    ✓ Correct
    Feedback:

μ = 8 % ;

σ = 3 % ;

n = 36 ;

x = 7 % ;

    S.E. = 3 / √ 36 = 0.5

Now,

    Zx = 7 - 8 / 0.5
    = -2

In [ ]:
(7 - 8) / (3 / (36 ** 0.5))

-2.0

p-Value of the Z-Score
--------

Calculate the p-value from the cumulative probability for the given Z-score using the Z-table.

In other words, find out the p-value for the `Z-score of -2.0`

(corresponding to the sample mean of 7%).

    0.9772

    0.0228

    0.5199

    0.4801

---------

    0.0228

    ✓ Correct
    Feedback:

The p-value corresponding to a Z-score of -2.0 is 0.0228

    z = -2.0 < 0,
    H1 : μ < 8 %,
    one tailed test

Making a Decision
---------

Make the decision on the basis of the p-value with respect to the given value of α (significance value).

    You reject the null hypothesis
    because the p-value is less than 0.05.

    You fail to reject the null hypothesis
    because the p-value is less than 0.05.

    You reject the null hypothesis
    because the p-value is more than 0.05.

    You fail to reject the null hypothesis
    because the p-value is more than 0.05.

---------

    You reject the null hypothesis
    because the p-value is less than 0.05.

    ✓ Correct
    Feedback:

Since the p-value of the Z-score of the sample mean is less than the given value of α = 0.05,

we `reject the null hypothesis`

    H0 : μ ≥ 8 %

In [ ]:
p = 0.0228
α = 0.05

p < α

True

# Types of Errors

- A type I-error, represented by α, occurs when you reject a true null hypothesis.

- A type-II error, represented by β, occurs when you fail to reject a false null hypothesis.

<br>

[![ss](https://cdn.upgrad.com/UpGrad/temp/c75cb725-4929-4bc0-bc90-9bbeadde779f/4.png)](https://statisticsbyjim.com/hypothesis-testing/types-errors-hypothesis-testing/)

Errors in Hypothesis Testing
---------

Mark all the correct options below.

    A type-I error occurs
    when a true null hypothesis is rejected.

    A type-I error occurs
    when the null hypothesis is not rejected
    when it is, in fact, incorrect.

    A type-II error occurs
    when the null hypothesis is rejected
    when it is, in fact, correct.

    A type II error occurs
    when the null hypothesis is not rejected
    when it is, in fact, incorrect.

----------

    A type-I error occurs
    when a true null hypothesis is rejected.

    ✓ Correct
    Feedback:

A type-I error occurs when the null hypothesis is true

(i.e., the sample mean lies in the acceptance region)

but you incorrectly reject it.

----------

    A type II error occurs
    when the null hypothesis is not rejected
    when it is, in fact, incorrect.

    ✓ Correct
    Feedback:

A type-II error occurs when the null hypothesis is not true

(i.e., the sample mean lies in the critical region)

but you incorrectly fail to reject it.

Types of Errors
----------

Suppose the null hypothesis is that a particular new process is as good as or better than the old one.

A type-I error would conclude that ___.

    The old process is as good as or better than the new one
    when, in fact, it is not.

    The old process is better than the new one
    when it really is so.

    The old process is better than the new one
    when, in fact, it is not.

    The new process is as good as or better than the new one
    when it really is so.

----------

    The old process is better than the new one
    when, in fact, it is not.

    ✓ Correct
    Feedback:

A type-I error refers to incorrectly rejecting a true null hypothesis.

    So, a type-1 error means that the null hypothesis is true,

i.e., the new process is as `good as or better` than the old one,

`but you reject it`, i.e., you conclude that the `old process is better`.